// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDI7VQyJqcr4DM_ZQL-U20cukiuLYXLnBA',
    appId: '1:1061267636183:web:16659941a45ad64dc59592',
    messagingSenderId: '1061267636183',
    projectId: 'ims1-5704f',
    authDomain: 'ims1-5704f.firebaseapp.com',
    storageBucket: 'ims1-5704f.firebasestorage.app',
    measurementId: 'G-C2Y190BVSN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZqNMnw4WjHHc3i9FymqYUoZnNl_TDxAA',
    appId: '1:1061267636183:android:aa6144d66f42fc97c59592',
    messagingSenderId: '1061267636183',
    projectId: 'ims1-5704f',
    storageBucket: 'ims1-5704f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCbSuRw8DUl0Fa5rIIVamcPbhqpEblq8A',
    appId: '1:1061267636183:ios:6a771a4713bfecffc59592',
    messagingSenderId: '1061267636183',
    projectId: 'ims1-5704f',
    storageBucket: 'ims1-5704f.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCbSuRw8DUl0Fa5rIIVamcPbhqpEblq8A',
    appId: '1:1061267636183:ios:6a771a4713bfecffc59592',
    messagingSenderId: '1061267636183',
    projectId: 'ims1-5704f',
    storageBucket: 'ims1-5704f.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDI7VQyJqcr4DM_ZQL-U20cukiuLYXLnBA',
    appId: '1:1061267636183:web:b3bf7849a639b0f8c59592',
    messagingSenderId: '1061267636183',
    projectId: 'ims1-5704f',
    authDomain: 'ims1-5704f.firebaseapp.com',
    storageBucket: 'ims1-5704f.firebasestorage.app',
    measurementId: 'G-CSCW6EGNXY',
  );

}